# Generated by Django 4.2.7 on 2023-11-11 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_author_id_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author_id',
        ),
    ]
